from text_models.bert_tasks.abstract_task import AbstractTask
from text_models.bert_tasks.masked_lm import MaskedLMTask
from text_models.bert_tasks.sts import STSTask
from text_models.bert_tasks.tsdae import TSDenoisingAutoEncoderTask
from text_models.bert_tasks.nsp import NextSentencePredictionTask
