from approaches.abstract_approach import AbstractApproach
from approaches.finetuning_tasks_test import FinetuningTasksTest
from approaches.intersection import IntersectionApproach
from approaches.simple import SimpleApproach
from approaches.tfidf import TfIdfApproach
