# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy==v0.961 black==v22.3.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Black
        run: |
          black . --check -l 120
      - name: Type checking
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive $(git ls-files '*.py')
